### ISSUE TITLE
Contributed style file from Ahmed Salem and Kamesh Arumugam

### ISSUE THREAD

**Issue by weiglemc** [oduwsdl/wsdlthesis#22]
Ahmed Salem sent me this style file, which he used for his successful dissertation in Feb 2018.  I've posted it in my webspace in case any of his edits are useful.

http://www.cs.odu.edu/~mweigle/files/ODUthesis_noCoAdvisor.sty

If you find something good and incorporate it, or find that you don't need this, let me know so that I can remove the file.  Thanks!

**Comment by ibnesayeed** [comment]
The signature line removal was a minor change that I did a while ago in my local copy. This style file does not have any other significant fixes. Other changes it has are either not in sync with the official style guide or do not match the journal model we use, so there is not much that can be reused from this style.
