### ISSUE TITLE
Is the cls current to the May 2018 version of the Guide?

### ISSUE THREAD

**Issue by machawk1** [oduwsdl/wsdlthesis#28]
The comments atop the `.cls` indicates that it is current to the November 2015 version of "The Old Dominion University Guide for the Preparation of These and Dissertation". The Guide was updated in May 2018 per the first page at the same URI referenced in the `.cls`. I recall some working being done on the `.cls` recently. Is the `.cls` current to the 2018 version of the Guide or still based on the 2015 version?

**Comment by ibnesayeed** [comment]
A thorough review of the guide and verification of the current output is needed, for which we have an ongoing ticket, #7. However, I think some changes were made to accommodate the new guide. I will update the commented line in the class file, though the same was updated in the README a while ago.
