### ISSUE TITLE
Organizing chapter in table of contents

### ISSUE THREAD

**Issue by hbake001** [oduwsdl/wsdlthesis#29]
I see the table of contents organize the chapters as it's shown in this screenshot: 

![image](https://user-images.githubusercontent.com/32879867/46918146-396b9600-cf9c-11e8-884a-c65bf37871d4.png)

I want to organize the chapters by introducing the name of the chapter then the sections like this

![image](https://user-images.githubusercontent.com/32879867/46918191-feb62d80-cf9c-11e8-99c9-f94bdf877f60.png)

How can I do this?

**Comment by ibnesayeed** [comment]
This is already the case. We enumerate chapters and sections in the ToC. If you want to include another level of nesting and enlist subsections then change `tocdepth` to `2` in the CLS file. Also, I think you are using an older version of the CLS file, you might want to use the latest one.

**Comment by hbake001** [comment]
I updated the CLS file and it's still the same behavior: 

![image](https://user-images.githubusercontent.com/32879867/46919204-c537ef00-cfa9-11e8-95db-61374affad76.png)

I even copied the most updated wsdlthesis class and it didn't work.

**Comment by ibnesayeed** [comment]
There is something seriously wrong somewhere else. The class file has never reported chapters with second-level numbering and the latest class file does not highlight links with outline colors as shown in your screenshots. Can you try cloning this repo separately and build it to see how the included sample files compile, then add some sections and subsections in one of the chapters to see the effect.

**Comment by ibnesayeed** [comment]
I would also check if you have every chapter starting with a `\chapter{}` command?

**Comment by hbake001** [comment]
@ibnesayeed  I see where the problem is.  Since I'm using windows I had to change the  `\inputAllFiles{chapters}` to 

`\input{chapters/01_introduction}
\input{chapters/02_background}
\input{chapters/03_relatedwork}
\input{chapters/04_results}
\input{chapters/05_conclusions}`

`\chapter{}` isn't working though.

**Comment by ibnesayeed** [comment]
I am surprised that `\chapter{Chapter Name}` command is not working for you. Can you freshly clone this repo and in the `main.tex` file change:

```tex
\inputAllFiles{chapters}
```

to:

```tex
\input{chapters/01_introduction}

\input{chapters/02_background}

\input{chapters/03_relatedwork}
```

and change:

```tex
\inputAllFiles{appendices}
```

to:

```tex
\input{appendices/a_species}
```

Then compile and see the result.

Next, add some sections and subsections in one of the chapters and see how it affects the ToC.

**Comment by hbake001** [comment]
It works, but I'm not sure what the problem is in my document.

**Comment by ibnesayeed** [comment]
In your document try changing:

```
\input{chapters/01_introduction}
\input{chapters/02_background}
\input{chapters/03_relatedwork}
\input{chapters/04_results}
\input{chapters/05_conclusions}
```

to:

```tex
\input{chapters/01_introduction}

\input{chapters/02_background}

\input{chapters/03_relatedwork}

\input{chapters/04_results}

\input{chapters/05_conclusions}
```

(Mind the extra empty lines between each `\input{}` command)

**Comment by hbake001** [comment]
It didn't work either. FYI my main.tex looks like this: 

```

\documentclass[master]{wsdlthesis}

\usepackage{custommacros}
\usepackage{setspace}

\usepackage{subcaption}

\input{config}

\begin{document}
\setrevision
\input{pages/vita}
\input{pages/abstract}
\beforepreface
\input{pages/preface}
\afterpreface
\begin{spacing}{2}
	
\input{chapters/01_introduction}

\input{chapters/02_background}

\input{chapters/03_relatedwork}

\input{chapters/04_results}

\input{chapters/05_conclusions}

\end{spacing}

\bibliographystyle{ieeetr}
\bibliography{ref}

\addtocontents{toc}{\vspace*{12pt}}
\addcontentsline{toc}{chapter}{REFERENCES}

\appendix

\input{appendices/a_species}

\newpage

\vitapage

\end{document}

```

**Comment by ibnesayeed** [comment]
Can you also verify that all your chapter files have a trailing new line, i.e., an empty line at the end? I am thinking along the lines of #21.

**Comment by hbake001** [comment]
I confirm that all chapter files have an empty line at the end.  Nothing was changed

**Comment by ibnesayeed** [comment]
Now, I am running out of ideas. If you come to the campus you can come see me in my office tomorrow.

**Comment by hbake001** [comment]
@ibnesayeed Yes sure.  Thanks for following up! appreciate your time.

**Comment by ibnesayeed** [comment]
@hbake001 can you have a look at #30 and see if that solves your problem temporarily?

**Comment by hbake001** [comment]
I commented the following code: 

                         \IfStrEq{\@chapapp}{APPENDIX}{%
                           \addcontentsline{toc}{section}%
                           {\protect\numberline{\thechapter.}\uppercase{#1}}%
                           {%
                             \addcontentsline{toc}{chapter}%
                           {\protect\numberline{\thechapter.}\uppercase{#1}}%
                         }}

but it didn't help in solving the issue.

**Comment by ibnesayeed** [comment]
I think it might help if we look at your code together in person to investigate what's going on.

**Comment by hbake001** [comment]
Are you available in the meantime?

**Comment by ibnesayeed** [comment]
Yes, I am in my office right now.

**Comment by ibnesayeed** [comment]
In person review fixed the issues, so closing this.
