### ISSUE TITLE
Chapter titles do not display in TOC

### ISSUE THREAD

**Issue by shawnmjones** [oduwsdl/wsdlthesis#30]
https://github.com/oduwsdl/wsdlthesis/blob/6e814c6b4a2ed50c6c7a4174937f6e39f1d28720/wsdlthesis.cls#L292-L296

The chapter titles do not display in the table of contents unless lines 292-294 and 296 are removed. I do not have any appendices yet, so I am unsure as to the side effects of removing those lines.

**Comment by shawnmjones** [comment]
This may be related to #29.

**Comment by ibnesayeed** [comment]
That is possibly very much related to the issue seen in #29 as you already pointed out. However, that conditional is in place because ODU thesis style guide has an inconsistent indentation between chapters and appendices.

**Comment by shawnmjones** [comment]
I cloned the latest repo and determined that I had old versions of `wsdlthesis.cls` and `custommacros.sty` with corrections for 4811ccd (mentioned in #24). It looks like I never got the fix from 56323dd (mentioned in #27).

When I replace the files in my repository with the most recent (6e814c6b4a2ed50c6c7a4174937f6e39f1d28720) class and style files, all works as expected.

Sorry for wasting your time.
