### ISSUE TITLE
Problem getting template in TeXworks

### ISSUE THREAD

**Issue by starkama** [oduwsdl/wsdlthesis#32]
Hello! I have followed the instruction to get the template but I am getting errors. I have to admit that I have not used LaTeX in about 6 years and I was advised to use it for my thesis. I am using TeXworks and if I just enter the "Getting Started" lines, it wants me to insert a \begin{document} prior to those lines. If I add that there is just another error that comes up.  Is this an issue with TeXworks or am I just doing something completely wrong? Thank you!

**Comment by ibnesayeed** [comment]
Which operating system are you using? The code and the documentation is optimized for Linux. Running it in any other OS would require a little bit of work and understanding of the setup, but doable.

**Comment by starkama** [comment]
Well that explains it! Just another reason I should have switched my computer over to Linux, I am using Windows. Do you have instruction as to how to set it up for Windows?

**Comment by ibnesayeed** [comment]
Please see https://github.com/oduwsdl/wsdlthesis/issues/26#issuecomment-405627770 and let me know if it helps or if you need any further help.
